# -*- coding: utf-8 -*-
"""PdfFileMerger.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SujRFAUJKli6XCaF9g6UcXtzhk64Y8EO
"""

pip install PyPDF2

from PyPDF2 import PdfFileReader,PdfFileMerger

file1=PdfFileReader("file1.pdf",strict=False)

file2=PdfFileReader("file2.pdf")

output=PdfFileMerger();

output.append(file1)
output.append(file2)

output.write("output_pdf.pdf")

